spring:
    application:
        name: user-service
    cloud:  
        stream:
            kafka:
                binder:
                    zkNodes: 10.1.67.188:2181
                    brokers: 10.1.67.188:9092
    redis:
        host: 10.1.67.188
        port: 6379
        database: 0
        pool:
            max-active: 10
            max-wait: 10
            max-idle: 8
        timeout: 0
server:
    port: 9999
datasource:
    url: jdbc:mysql://10.1.67.188:3306/users?useUnicode=true&characterEncoding=utf8
    driverclass: com.mysql.jdbc.Driver
    username: admin
    password: admin
eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://10.1.67.188:8761/eureka/,http://10.1.67.188:8762/eureka/
        healthCheck:
            enable: true
management:
  port: 12222
  health:
    refresh:
      enabled: true
info:
    app:
        name: "user"

logging:
  level: error

---
spring: 
 profiles: prod

weather: "bonjour1 jet" 
