spring:
    profiles: prod
server:
    port: 9999
eureka:
    instance:
         instanceId: ${Random.value}
         prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_LIST}
